server:
  port: 8084
spring:
  datasource:
    username: root
    password: "Uchain1007"

  servlet:
    multipart:
      enabled: true
      # 设置文件大小限制  10MB
      max-file-size: 102400000
      # 设置总上传数据总大小 30MB
      max-request-size: 307200000

upload:
  apply-file-name: "立项申请主要内容"
  concluding-file-name: "结题报告"
  experiment-report-file-name: "项目实验报告"
  apply-dir: "/usr/local/uchain/apply_dir"
  apply-dir-2: "/usr/local/uchain/apply_dir_2"
  pdf-temp-dir: "/usr/local/uchain/pdf_temp_dir"
  conclusion-dir: "/usr/local/uchain/conclusion_dir"
  material_sample: "/usr/local/uchain/material_sample"
  conclusion-pdf: "/usr/local/uchain/conclusion_pdf"
  conclusion-annex: "/usr/local/uchain/conclusion_annex"
  achievement-annex: "/usr/local/uchain/achievement_annex"
  news-images: "/usr/local/uchain/news_images"
download:
  certificate-excel-download: "/usr/local/uchain/excel-temp"
file:
#  ipaddress: "http://192.168.43.29:8083"
#  ip-address: "http://192.168.43.153:8083"
  ip-address: "http://192.168.109.88:8083"
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl