server:
  port: 8083
spring:
  datasource:
    username: root
    password: "123456"

  servlet:
    multipart:
      enabled: true
      # 设置文件大小限制  10MB
      max-file-size: 102400000
      # 设置总上传数据总大小 30MB
      max-request-size: 307200000

upload:
  apply-file-name: "立项申请主要内容"
  concluding-file-name: "结题报告"
  apply-dir: "E:/IdeaProjects/OpenExperiment/src/main/resources/apply_dir"
  apply-dir-2: "E:/IdeaProjects/OpenExperiment/src/main/resources/apply_dir_2"
  pdf-temp-dir: "E:/IdeaProjects/OpenExperiment/src/main/resources/pdf_temp_dir"
  conclusion-dir: "E:/IdeaProjects/OpenExperiment/src/main/resources/conclusion_dir"
  material_sample: "E:/IdeaProjects/OpenExperiment/src/main/resources/material_sample"

file:
  ip-address: "http://192.168.1.101:8083"


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl